server:
  port: 8080
logging:
  config: classpath:logback-spring-local.xml
  level:
    org:
      hibernate:
        SQL: DEBUG
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/post_solo?useUnicode=true&characterEncoding=UTF-8
jwtpassword:
  source: ${JWT_SECRET_KEY}

